--vim.g.nobody_colorscheme = "gruvbox"
--
--local function colorMyPencils()
--	vim.g.gruvbox_contras_dark = 'hard'
--	if vim.o.termguicolors then
--		vim.o.t_8f = "\\<Esc>[38;2;%lu;%lu;%lum"
--		vim.o.t_8b = "\\<Esc>[48;2;%lu;%lu;%lum"
--	end
--	vim.g.gruvbox_invert_selection = '0'
--	vim.opt.background = "dark"
--
--	vim.cmd("colorscheme " .. vim.g.nobody_colorscheme)
--end
--colorMyPencils()
